### ISSUE TITLE
Head doesn't reset per page generation when using classic static + nuxt 2.11, but does in 2.14.4

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt-community/speedcurve-module#4]
When using this module on a Nuxt 2.11 site (target: server, mode: 'universal', 'generate') the metas don't seem to be reset per page generation.

It's almost like we need to manually check for the meta to exist ourselves which is strange.
https://github.com/nuxt-community/speedcurve-module/blob/master/lib/templates/plugin.js#L80

![image](https://user-images.githubusercontent.com/2112282/91791881-dad45300-ebd9-11ea-9e14-70bfee10f79e.png)

**After updating my site to Nuxt 2.14.4, it looks fine.  Did something change since 2.11?**

**Comment by hecktarzuli** [comment]
@pi0 @pimlie was there some type of problem with metas not getting reset per page (and then get resolved) between 2.11 and 2.14.4?

**Comment by pi0** [comment]
Hi @hecktarzuli indeed it was a bug fixed by 2.12 (https://github.com/nuxt/nuxt.js/pull/6807)

You can add a notice to the docs or do https://github.com/nuxt-community/gtm-module/commit/43f41c8e7ce58ca40476cc9624be8464908b2d91
